services:
    Gally\OroPlugin\Decorator\ProductIndexFieldsProvider:
        decorates: oro_product.provider.index_fields
        arguments:
            - '@.inner'

    Gally\OroPlugin\Provider\CatalogProvider:
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@oro_website.provider.website_localization'
            - '@oro_pricing.provider.website_currency_provider'
        tags:
            - { name: 'gally.dataprovider', entity: 'catalog' }

    Gally\OroPlugin\Provider\SourceFieldProvider:
        arguments:
            - '@oro_website_search.provider.search_mapping'
            - '@oro_entity.entity_alias_resolver'
            - '@oro_entity_config.provider.entity'
            - '@Gally\OroPlugin\Provider\CatalogProvider'
            - '@oro_website_search.placeholder.registry'
            - '@translator'
            - '@oro_locale.settings'
            - '%gally_config.entity_mapping%'
            - '%gally_config.attribute_mapping%'
            - '%gally_config.attribute_type_mapping%'
        tags:
            - { name: 'gally.dataprovider', entity: 'sourceField' }

    Gally\OroPlugin\Provider\SourceFieldOptionProvider:
        arguments:
            - '@oro_website_search.provider.search_mapping'
            - '@Gally\OroPlugin\Provider\CatalogProvider'
            - '@oro_locale.settings'
            - '@doctrine.orm.entity_manager'
            - '@oro_entity_extend.enum_type_helper'
            - '@Gally\OroPlugin\Provider\SourceFieldProvider'
        tags:
            - { name: 'gally.dataprovider', entity: 'sourceFieldOption' }

    Gally\OroPlugin\Command\StructureSync:
        arguments:
            - '@Gally\Sdk\Service\StructureSynchonizer'
            - !tagged_iterator { tag: 'gally.dataprovider', index_by: 'entity' }
        tags:
            - { name: console.command }

    Gally\OroPlugin\EventListener\WebsiteSearchWebCatalogIndexerListener:
        arguments:
            - '@oro_website_search.manager.website_context_manager'
            - '@doctrine'
            - '@oro_web_catalog.web_catalog_provider'
            - '@oro_locale.helper.localization'
        tags:
            - { name: kernel.event_listener, event: oro_website_search.event.index_entity.contentnode, method: onWebsiteSearchIndex, priority: -255 }

    Gally\OroPlugin\EventListener\WebsiteSearchInventoryLevelIndexerListener:
        arguments:
            - '@doctrine'
            - '@oro_warehouse.provider.enabled_warehouses_provider'
        tags:
            - { name: kernel.event_listener, event: oro_website_search.event.index_entity.product, method: onWebsiteSearchIndex, priority: -255 }

    Gally\OroPlugin\Engine\IndexDataProvider:
        arguments:
            - '@event_dispatcher'
            - '@oro_entity.entity_alias_resolver'
            - '@oro_website_search.placeholder_decorator'
            - '@oro_ui.html_tag_helper'
            - '@oro_website_search.helper.placeholder_helper'
            - '@oro_entity.doctrine_helper'
            - '@oro_locale.helper.localization'
            - '@oro_pricing.provider.website_currency_provider'
            - '@oro_website_search.manager.website_context_manager'
            - '@oro_config.manager'
            - '@oro_featuretoggle.checker.feature_checker'
            - '@oro_website_search.provider.search_mapping'
            - '@doctrine.orm.entity_manager'
            - '@oro_entity_extend.enum_type_helper'
            - '%gally_config.attribute_mapping%'

    Gally\OroPlugin\Engine\Indexer:
        arguments:
            - '@oro_entity.doctrine_helper'
            - '@oro_website_search.provider.search_mapping'
            - '@oro_website_search.engine.entity_dependencies_resolver'
            - '@Gally\OroPlugin\Engine\IndexDataProvider'
            - '@oro_website_search.placeholder_decorator'
            - '@oro_website_search.indexer.input_validator'
            - '@event_dispatcher'
            - '@oro_website_search.regex_placeholder_decorator'
            - '@oro_website.provider.website_localization'
            - '@Gally\OroPlugin\Provider\CatalogProvider'
            - '@Gally\OroPlugin\Provider\SourceFieldProvider'
            - '@Gally\Sdk\Service\IndexOperation'
        #        calls:
        #            - ['setLogger', ['@logger']]
        #            - ['setBatchSize', ['%oro_website_search.indexer_batch_size%']]
        tags:
            - { name: 'oro_website_search.engine.indexer', engine_name: 'gally' }
