services:
    oro_website_search.indexer:
        class: 'Oro\Bundle\SearchBundle\Engine\IndexerInterface'
        arguments:
            - !tagged_locator { tag: 'oro_website_search.engine.indexer', index_by: 'engine_name' }
            - '@oro_website_search.engine.parameters'
        factory: [ 'Gally\OroPlugin\Indexer\IndexerFactory', 'create' ]

    Gally\OroPlugin\Decorator\ProductIndexFieldsProvider:
        decorates: oro_product.provider.index_fields
        arguments:
            - '@.inner'
            - '@Gally\OroPlugin\Service\ContextProvider'

    Gally\OroPlugin\Indexer\Provider\CatalogProvider:
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@oro_website.provider.website_localization'
            - '@oro_pricing.provider.website_currency_provider'
            - '@Gally\OroPlugin\Config\ConfigManager'
        tags:
            - { name: 'gally.dataprovider', entity: 'catalog' }

    Gally\OroPlugin\Indexer\Provider\SourceFieldProvider:
        arguments:
            - '@Gally\OroPlugin\Provider\SearchMappingProvider'
            - '@oro_entity.entity_alias_resolver'
            - '@oro_entity_config.provider.entity'
            - '@Gally\OroPlugin\Indexer\Provider\CatalogProvider'
            - '@oro_website_search.placeholder.registry'
            - '@Gally\OroPlugin\Repository\TranslationRepository'
            - '@oro_locale.settings'
            - '%gally_config.entity_mapping%'
            - '%gally_config.attribute_type_mapping%'
            - '%gally_config.attribute_mapping%'
            - '%gally_config.oro_system_attribute%'
            - '%gally_config.field_to_skip%'
        tags:
            - { name: 'gally.dataprovider', entity: 'sourceField' }

    Gally\OroPlugin\Indexer\Provider\SourceFieldOptionProvider:
        arguments:
            - '@Gally\OroPlugin\Provider\SearchMappingProvider'
            - '@Gally\OroPlugin\Indexer\Provider\CatalogProvider'
            - '@oro_locale.settings'
            - '@doctrine.orm.entity_manager'
            - '@oro_entity_extend.enum_type_helper'
            - '@Gally\OroPlugin\Indexer\Provider\SourceFieldProvider'
        tags:
            - { name: 'gally.dataprovider', entity: 'sourceFieldOption' }

    Gally\OroPlugin\Command\StructureSync:
        arguments:
            - '@Gally\Sdk\Service\StructureSynchonizer'
            - !tagged_iterator { tag: 'gally.dataprovider', index_by: 'entity' }
        tags:
            - { name: console.command }

    Gally\OroPlugin\Indexer\EventListener\WebsiteSearchWebCatalogIndexerListener:
        arguments:
            - '@oro_website_search.manager.website_context_manager'
            - '@doctrine'
            - '@Gally\OroPlugin\Config\ConfigManager'
            - '@oro_web_catalog.web_catalog_provider'
            - '@oro_locale.helper.localization'
        tags:
            - { name: kernel.event_listener, event: oro_website_search.event.index_entity.contentnode, method: onWebsiteSearchIndex, priority: -255 }

    Gally\OroPlugin\Indexer\EventListener\WebsiteSearchChildDataIndexerListener:
        arguments:
            - '@Gally\OroPlugin\Config\ConfigManager'
        tags:
            - { name: kernel.event_listener, event: oro_website_search.event.index_entity.product, method: onWebsiteSearchIndex, priority: -255 }

    Gally\OroPlugin\Indexer\Normalizer\BrandDataNormalizer:
        tags:
            - { name: gally.indexer_normalizer }

    Gally\OroPlugin\Indexer\Normalizer\PriceDataNormalizer:
        arguments:
            - '@oro_entity.doctrine_helper'
            - '@oro_config.manager'
            - '@oro_featuretoggle.checker.feature_checker'
            - '@oro_pricing.provider.website_currency_provider'
            - '@Gally\OroPlugin\Resolver\PriceGroupResolver'
        tags:
            - { name: gally.indexer_normalizer }

    Gally\OroPlugin\Indexer\Normalizer\CategoryDataNormalizer:
        arguments:
            - '@oro_entity.doctrine_helper'
            - '@oro_locale.helper.localization'
        tags:
            - { name: gally.indexer_normalizer }

    Gally\OroPlugin\Indexer\Normalizer\SelectDataNormalizer:
        arguments:
            - '@oro_entity.doctrine_helper'
            - '@oro_entity_extend.enum_type_helper'
        tags:
            - { name: gally.indexer_normalizer }

    Gally\OroPlugin\Indexer\Normalizer\VisibilityDataNormalizer:
        tags:
            - { name: gally.indexer_normalizer }

    Gally\OroPlugin\Indexer\Normalizer\StockDataNormalizer:
        tags:
            - { name: gally.indexer_normalizer }

    Gally\OroPlugin\Indexer\Normalizer\BooleanDataNormalizer:
        arguments:
            - '@oro_entity_config.provider.entity'
        tags:
            - { name: gally.indexer_normalizer }

    Gally\OroPlugin\Indexer\Normalizer\DatetimeDataNormalizer:
        tags:
            - { name: gally.indexer_normalizer }

    Gally\OroPlugin\Indexer\IndexDataProvider:
        arguments:
            - '@event_dispatcher'
            - '@oro_entity.entity_alias_resolver'
            - '@oro_website_search.placeholder_decorator'
            - '@oro_ui.html_tag_helper'
            - '@oro_website_search.helper.placeholder_helper'
            - '@oro_website_search.manager.website_context_manager'
            - '@Gally\OroPlugin\Service\ContextProvider'
            - '%gally_config.attribute_mapping%'
            - !tagged_iterator { tag: 'gally.indexer_normalizer' }

    Gally\OroPlugin\Indexer\Registry\IndexRegistry: ~
    
    Gally\OroPlugin\Decorator\AddIndexNameInContext:
        decorates: oro_website_search.async.indexer.message_granularizer.reindex
        arguments:
            - '@.inner'
            - '@Gally\OroPlugin\Indexer\Registry\IndexRegistry'
    
    Gally\OroPlugin\Decorator\AddIndexNameInReindexMessage:
        decorates: oro_website_search.indexer.input_validator
        arguments:
            - '@.inner'
            
    Gally\OroPlugin\Indexer\Indexer:
        arguments:
            - '@oro_entity.doctrine_helper'
            - '@Gally\OroPlugin\Provider\SearchMappingProvider'
            - '@oro_website_search.engine.entity_dependencies_resolver'
            - '@Gally\OroPlugin\Indexer\IndexDataProvider'
            - '@oro_website_search.placeholder_decorator'
            - '@oro_website_search.indexer.input_validator'
            - '@event_dispatcher'
            - '@oro_website_search.regex_placeholder_decorator'
            - '@oro_website.provider.website_localization'
            - '@Gally\OroPlugin\Indexer\Provider\CatalogProvider'
            - '@Gally\OroPlugin\Indexer\Provider\SourceFieldProvider'
            - '@Gally\Sdk\Service\IndexOperation'
            - '@Gally\OroPlugin\Config\ConfigManager'
            - '@Gally\OroPlugin\Indexer\Registry\IndexRegistry'
            - '@oro_website_search.entity_identifier_repository'
        calls:
            - ['setBatchSize', ['%oro_website_search.indexer_batch_size%']]
        tags:
            - { name: 'oro_website_search.engine.indexer', engine_name: 'gally' }
            - { name: kernel.event_listener, event: oro_website_search.before_reindex, method: beforeReindex, priority: -255 }
            - { name: kernel.event_listener, event: oro_website_search.after_reindex, method: afterReindex, priority: -255 }
