services:
    Gally\Sdk\Client\TokenCacheManagerInterface:
        class: Gally\OroPlugin\Config\TokenCacheManager
        calls:
            - [ setCache, [ '@oro.gally.cache' ] ]
    
    Gally\Sdk\Client\Configuration:
        factory: ['\Gally\OroPlugin\Config\ConfigurationFactory', 'create']
        lazy: true
        arguments:
            - '%oro_website_search.engine_dsn%'

    Gally\Sdk\Service\StructureSynchonizer:
        arguments:
            - '@Gally\Sdk\Client\Configuration'
            - '@Gally\Sdk\Client\TokenCacheManagerInterface'

    Gally\Sdk\Service\IndexOperation:
        arguments:
            - '@Gally\Sdk\Client\Configuration'
            - '@Gally\Sdk\Client\TokenCacheManagerInterface'

    Gally\Sdk\Service\SearchManager:
        arguments:
            - '@Gally\Sdk\Client\Configuration'
            - '@Gally\Sdk\Client\TokenCacheManagerInterface'
