services:
    Gally\Sdk\Client\Configuration:
        factory: ['\Gally\OroPlugin\Factory\ConfigurationFactory', 'create']
        lazy: true
        arguments:
            - '@Gally\OroPlugin\Config\ConfigManager'

    Gally\Sdk\Service\StructureSynchonizer:
        arguments:
            - '@Gally\Sdk\Client\Configuration'

    Gally\Sdk\Service\IndexOperation:
        arguments:
            - '@Gally\Sdk\Client\Configuration'

    Gally\Sdk\Service\SearchManager:
        arguments:
            - '@Gally\Sdk\Client\Configuration'
