services:
    Gally\OroPlugin\Search\SearchRegistry: ~

    Gally\OroPlugin\Decorator\SavePriceFilterUnit:
        decorates: oro_pricing.filter.frontend_product_price
        arguments:
            - '@.inner'
            - '@Gally\OroPlugin\Search\SearchRegistry'

    Gally\OroPlugin\Search\ContextProvider:
        arguments:
            - '@oro_website.manager'
            - '@oro_locale.helper.localization'
            - '@Gally\OroPlugin\Indexer\Provider\CatalogProvider'
            - '@oro_web_catalog.request_web_content_variant_provider'

    Gally\OroPlugin\Search\ExpressionVisitor:
        arguments:
            - '%gally_config.attribute_mapping%'

    Gally\OroPlugin\Search\GallyRequestBuilder:
        arguments:
            - '@Gally\OroPlugin\Search\ContextProvider'
            - '@Gally\OroPlugin\Search\ExpressionVisitor'
            - '@Gally\OroPlugin\Search\SearchRegistry'
            - '@Gally\OroPlugin\Resolver\PriceGroupResolver'
            - '@oro_website_search.placeholder.registry'

    Gally\OroPlugin\Search\Filter\SelectFilter:
        public: false
        arguments:
            - '@form.factory'
            - '@oro_filter.filter_utility'
            - '@oro_entity.manager.dictionary.api'
        tags:
            - { name: oro_search.extension.search_filter.filter, type: gally-select }

    Gally\OroPlugin\Search\Filter\Form\SelectFormFilter:
        tags:
            - { name: form.type, alias: gally_search_type_select_filter }

    Gally\OroPlugin\Search\SearchEngine:
        arguments:
            - '@event_dispatcher'
            - '@Gally\OroPlugin\Resolver\QueryPlaceholderResolver'
            - '@oro_website_search.provider.search_mapping'
            #            - '@oro_website_elastic_search.engine.index_agent'
            #            - '@oro_website_elastic_search.request_builder.registry'
            - '@Gally\Sdk\Service\SearchManager'
            - '@Gally\OroPlugin\Search\GallyRequestBuilder'
            - '@Gally\OroPlugin\Search\SearchRegistry'
            - '%gally_config.attribute_mapping%'
        calls:
            - ['setMapper', ['@oro_website_search.engine.mapper']]
        tags:
            - { name: 'oro_website_search.engine', engine_name: 'gally' }

    Gally\OroPlugin\Search\CustomerPartialUpdateDriver:
        arguments:
            - '@oro_website_search.provider.placeholder_provider'
            - '@oro_visibility.visibility.provider.product_visibility_provider'
            - '@oro_entity.doctrine_helper'
        tags:
            - { name: 'oro_website_search.customer_partial_update_driver', engine_name: 'gally' }

    Gally\OroPlugin\Search\Extension\GallyDataGridExtension:
        arguments:
            - '@oro_website_search.engine.parameters'
            - '@Gally\Sdk\Service\SearchManager'
            - '@Gally\OroPlugin\Search\SearchRegistry'
        tags:
            - { name: oro_datagrid.extension }
