parameters:
    gally_config.entity_mapping:
        contentnode: 'category'
    gally_config.attribute_type_mapping:
        !php/const Oro\Bundle\SearchBundle\Query\Query::TYPE_TEXT: !php/const \Gally\Sdk\Entity\SourceField::TYPE_TEXT
        !php/const Oro\Bundle\SearchBundle\Query\Query::TYPE_DECIMAL: !php/const \Gally\Sdk\Entity\SourceField::TYPE_FLOAT
        !php/const Oro\Bundle\SearchBundle\Query\Query::TYPE_INTEGER: !php/const \Gally\Sdk\Entity\SourceField::TYPE_INT
        !php/const Oro\Bundle\SearchBundle\Query\Query::TYPE_DATETIME: !php/const \Gally\Sdk\Entity\SourceField::TYPE_DATE

services:
    Gally\OroPlugin\Placeholder\PlaceholderDecorator:
        arguments:
            - '@oro_website_search.placeholder.registry'

    Gally\OroPlugin\Resolver\QueryPlaceholderResolver:
        public: false
        arguments:
            - '@Gally\OroPlugin\Placeholder\PlaceholderDecorator'

imports:
    - { resource: services/sdk.yml }
    - { resource: services/indexer.yml }
    - { resource: services/search.yml }
