parameters:
    gally_config.entity_mapping:
        contentnode: 'category'
    gally_config.attribute_type_mapping:
        text: !php/const \Gally\Sdk\Entity\SourceField::TYPE_TEXT
        string: !php/const \Gally\Sdk\Entity\SourceField::TYPE_TEXT
        decimal: !php/const \Gally\Sdk\Entity\SourceField::TYPE_FLOAT
        float: !php/const \Gally\Sdk\Entity\SourceField::TYPE_FLOAT
        integer: !php/const \Gally\Sdk\Entity\SourceField::TYPE_INT
        datetime: !php/const \Gally\Sdk\Entity\SourceField::TYPE_DATE
        boolean: !php/const \Gally\Sdk\Entity\SourceField::TYPE_BOOLEAN
        enum: !php/const \Gally\Sdk\Entity\SourceField::TYPE_SELECT
        multiEnum: !php/const \Gally\Sdk\Entity\SourceField::TYPE_SELECT
    gally_config.attribute_mapping:
        system_entity_id: id
        names: name
        descriptions: description
        type: oro_type
    gally_config.oro_system_attribute:
        - status
        - assigned_to
        - manually_added_to
        - category_path
        - category_paths
        - is_hide_configurable
        - is_show_single_variant
        - is_variant
        - is_visible_by_default
        - oro_type
        - visibility_anonymous
        - visibility_new
        - visible_for_customer
        - hidden_for_customer
    gally_config.field_to_skip:
        - id                               # Id field will be automatically added @see \Gally\OroPlugin\Indexer\Provider\SourceFieldProvider::provide
        - visibility_customer.CUSTOMER_ID  # Field managed manually @see src/Resources/config/oro/website_search.yml
        - inv_status                       # Field managed manually @see oro/src/packages/GallyPlugin/src/Engine/IndexDataProvider.php
        - inventory_status                 # Field managed manually @see oro/src/packages/GallyPlugin/src/Engine/IndexDataProvider.php
        - inv_qty                          # Field managed manually @see oro/src/packages/GallyPlugin/src/Engine/IndexDataProvider.php
        - brand_LOCALIZATION_ID            # Brand field is managed as a select

services:
    oro.gally.cache:
        parent: oro.data.cache
        arguments:
            $defaultLifetime: 1800
        tags:
            - { name: 'cache.pool', namespace: 'gally_cache' }
    
    Gally\OroPlugin\Config\ConfigManager:
        arguments:
            - '@doctrine'
            - '@oro_config.manager'
            - '@oro_security.encoder.default'

    Gally\OroPlugin\Service\ContextProvider:
        arguments:
            - '@oro_config.manager'
            - '@oro_website.manager'
            - '@oro_locale.helper.localization'
            - '@Gally\OroPlugin\Indexer\Provider\CatalogProvider'
            - '@oro_web_catalog.request_web_content_variant_provider'

    Gally\OroPlugin\Provider\SearchMappingProvider:
        arguments:
            - '@event_dispatcher'
            - '@oro_website_search.mapping_configuration.provider'
            - '@oro_website_search.cache.mapping_configuration'
            - '@Gally\OroPlugin\Service\ContextProvider'
            - 'oro_search.mapping_config.gally:'
            - "@=service('oro_website_search.engine.parameters').getEngineName()"
            - 'oro_website_search.event.website_search_mapping.configuration'

    Gally\OroPlugin\Placeholder\PlaceholderDecorator:
        arguments:
            - '@oro_website_search.placeholder.registry'

    Gally\OroPlugin\Resolver\QueryPlaceholderResolver:
        class: Oro\Bundle\WebsiteSearchBundle\Resolver\QueryPlaceholderResolver
        public: false
        arguments:
            - '@Gally\OroPlugin\Placeholder\PlaceholderDecorator'

    Gally\OroPlugin\Resolver\PriceGroupResolver:
        public: false

    oro_website_elastic_search.voter.elastic_search_engine_feature_voter:
        class: Gally\OroPlugin\Voter\ElasticSearchEngineFeatureVoter
        arguments:
            - '@oro_website_search.engine.parameters'
        tags:
            - { name: oro_featuretogle.voter }

    Oro\Bundle\CustomerRecommendationBundle\Checker\Voter\CustomerRecommendationVoter:
        class: Gally\OroPlugin\Voter\ElasticSearchEngineFeatureVoter
        arguments:
            - '@oro_website_search.engine.parameters'
        tags:
            - { name: oro_featuretogle.voter }

imports:
    - { resource: services/sdk.yml }
    - { resource: services/indexer.yml }
    - { resource: services/search.yml }
