parameters:
    gally: # Todo manage conf from DNS Env var
        baseUri: 'https://api.gally.local'
        user: 'admin@example.com'
        password: 'apassword'

services:
    Gally\OroPlugin\Placeholder\PlaceholderDecorator:
        arguments:
            - '@oro_website_search.placeholder.registry'

    Gally\OroPlugin\Resolver\QueryPlaceholderResolver:
        public: false
        arguments:
            - '@Gally\OroPlugin\Placeholder\PlaceholderDecorator'

imports:
    - { resource: services/sdk.yml }
    - { resource: services/indexer.yml }
    - { resource: services/search.yml }
