imports:
    - { resource: services/sdk.yml }

parameters:
    gally: # Todo manage conf from DNS Env var
        baseUri: 'https://api.gally.local'
        user: 'admin@example.com'
        password: 'apassword'

services:
    Gally\OroPlugin\Placeholder\PlaceholderDecorator:
        arguments:
            - '@oro_website_search.placeholder.registry'

    Gally\OroPlugin\Provider\CatalogProvider:
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@oro_website.provider.website_localization'
            - '@oro_pricing.provider.website_currency_provider'

    Gally\OroPlugin\Provider\SourceFieldProvider:
        arguments:
            - '@oro_website_search.provider.search_mapping'
            - '@oro_entity.entity_alias_resolver'
            - '@oro_entity_config.provider.entity'
            - '@Gally\OroPlugin\Provider\CatalogProvider'
            - '@oro_website_search.placeholder.registry'
            - '@translator'
            - '@oro_locale.settings'

    Gally\OroPlugin\Provider\SourceFieldOptionProvider:
        arguments:
            - '@oro_website_search.provider.search_mapping'
            - '@Gally\OroPlugin\Provider\CatalogProvider'
            - '@oro_locale.settings'
            - '@doctrine.orm.entity_manager'
            - '@oro_entity_extend.enum_type_helper'
            - '@Gally\OroPlugin\Provider\SourceFieldProvider'

    Gally\OroPlugin\Command\StructureSync:
        arguments:
            - '@Gally\OroPlugin\Provider\CatalogProvider'
            - '@Gally\OroPlugin\Provider\SourceFieldProvider'
            - '@Gally\OroPlugin\Provider\SourceFieldOptionProvider'
            - '@Gally\Sdk\Service\StructureSynchonizer'
        tags:
            - { name: console.command }

    Gally\OroPlugin\EventListener\WebsiteSearchWebCatalogIndexerListener:
        arguments:
            - '@oro_website_search.manager.website_context_manager'
            - '@doctrine'
            - '@oro_web_catalog.web_catalog_provider'
            - '@oro_locale.helper.localization'
        tags:
            - { name: kernel.event_listener, event: oro_website_search.event.index_entity.contentnode, method: onWebsiteSearchIndex, priority: -255 }

    Gally\OroPlugin\EventListener\WebsiteSearchInventoryLevelIndexerListener:
        arguments:
            - '@doctrine'
            - '@oro_warehouse.provider.enabled_warehouses_provider'
        tags:
            - { name: kernel.event_listener, event: oro_website_search.event.index_entity.product, method: onWebsiteSearchIndex, priority: -255 }

    oro_website_search.engine.gally.index_data:
        class: 'Gally\OroPlugin\Engine\IndexDataProvider'
        arguments:
            - '@event_dispatcher'
            - '@oro_entity.entity_alias_resolver'
            - '@oro_website_search.placeholder_decorator'
            - '@oro_ui.html_tag_helper'
            - '@oro_website_search.helper.placeholder_helper'
            - '@oro_entity.doctrine_helper'
            - '@oro_locale.helper.localization'
            - '@oro_pricing.provider.website_currency_provider'
            - '@oro_website_search.manager.website_context_manager'
            - '@oro_config.manager'
            - '@oro_featuretoggle.checker.feature_checker'
            - '@oro_website_search.provider.search_mapping'
            - '@Gally\OroPlugin\Provider\CatalogProvider'
            - '@oro_locale.settings'
            - '@doctrine.orm.entity_manager'
            - '@oro_entity_extend.enum_type_helper'
            - '@Gally\OroPlugin\Provider\SourceFieldProvider'

    Gally\OroPlugin\Registry\SearchRegistry: ~

    Gally\OroPlugin\EventListener\WebsiteSearchAfterListener:
        tags:
            - { name: kernel.event_listener, event: oro_website_search.after_search, method: onSearchAfter }

    oro_website_search.gally.indexer:
        class: 'Gally\OroPlugin\Engine\Indexer'
        arguments:
            - '@oro_entity.doctrine_helper'
            - '@oro_website_search.provider.search_mapping'
            - '@oro_website_search.engine.entity_dependencies_resolver'
            - '@oro_website_search.engine.gally.index_data'
            - '@oro_website_search.placeholder_decorator'
            - '@oro_website_search.indexer.input_validator'
            - '@event_dispatcher'
            - '@oro_website_search.regex_placeholder_decorator'
            - '@oro_website.provider.website_localization'
            - '@oro_web_catalog.web_catalog_provider'
            - '@Gally\OroPlugin\Provider\CatalogProvider'
            - '@Gally\OroPlugin\Provider\SourceFieldProvider'
            - '@Gally\Sdk\Service\IndexOperation'
#        calls:
#            - ['setLogger', ['@logger']]
#            - ['setBatchSize', ['%oro_website_search.indexer_batch_size%']]
        tags:
            - { name: 'oro_website_search.engine.indexer', engine_name: 'gally' }

    Gally\OroPlugin\RequestBuilder\GallyRequestBuilder: ~

    Gally\OroPlugin\Resolver\QueryPlaceholderResolver:
        public: false
        arguments:
            - '@Gally\OroPlugin\Placeholder\PlaceholderDecorator'

    oro_website_search.gally.engine:
        class: 'Gally\OroPlugin\Engine\SearchEngine'
        arguments:
            - '@event_dispatcher'
            - '@Gally\OroPlugin\Resolver\QueryPlaceholderResolver'
            - '@oro_website_search.provider.search_mapping'
#            - '@oro_website_elastic_search.engine.index_agent'
#            - '@oro_website_elastic_search.request_builder.registry'
            - '@Gally\Sdk\Service\SearchManager'
            - '@Gally\OroPlugin\RequestBuilder\GallyRequestBuilder'
        calls:
            - ['setMapper', ['@oro_website_search.engine.mapper']]
        tags:
            - { name: 'oro_website_search.engine', engine_name: 'gally' }

    Gally\OroPlugin\Extension\SortableAttributesExtension:
        arguments:
            - '@Gally\Sdk\Service\SearchManager'
            - '@Gally\OroPlugin\EventListener\WebsiteSearchSaveAggregationsListener'
        tags:
            - { name: oro_datagrid.extension }

    # Todo why this ??
    Gally\OroPlugin\Decorator\ProductIndexFieldsProvider:
        decorates: oro_product.provider.index_fields
        arguments:
            - '@.inner'

    # Todo why this ??
    oro_product.provider.index_fields:
        class: 'Oro\Bundle\ProductBundle\Search\ProductIndexFieldsProvider'
        public: false
        # These attributes are forced to be indexed as a separate fields because they are used at main product grid of front store
        calls:
            - [addForceIndexed,  ['sku']]
            - [addForceIndexed,  ['names']]
            - [addForceIndexed,  ['shortDescriptions']]
            - [addForceIndexed,  ['newArrival']]
