parameters:
    gally_config.entity_mapping:
        contentnode: 'category'
    gally_config.attribute_mapping:
        system_entity_id: id
        names: name
        descriptions: description
    gally_config.attribute_type_mapping:
        text: !php/const \Gally\Sdk\Entity\SourceField::TYPE_TEXT
        string: !php/const \Gally\Sdk\Entity\SourceField::TYPE_TEXT
        decimal: !php/const \Gally\Sdk\Entity\SourceField::TYPE_FLOAT
        float: !php/const \Gally\Sdk\Entity\SourceField::TYPE_FLOAT
        integer: !php/const \Gally\Sdk\Entity\SourceField::TYPE_INT
        datetime: !php/const \Gally\Sdk\Entity\SourceField::TYPE_DATE
        boolean: !php/const \Gally\Sdk\Entity\SourceField::TYPE_BOOLEAN
        enum: !php/const \Gally\Sdk\Entity\SourceField::TYPE_SELECT
        multiEnum: !php/const \Gally\Sdk\Entity\SourceField::TYPE_SELECT

services:
    Gally\OroPlugin\Placeholder\PlaceholderDecorator:
        arguments:
            - '@oro_website_search.placeholder.registry'

    Gally\OroPlugin\Resolver\QueryPlaceholderResolver:
        public: false
        arguments:
            - '@Gally\OroPlugin\Placeholder\PlaceholderDecorator'

    oro_website_elastic_search.voter.elastic_search_engine_feature_voter:
        class: Gally\OroPlugin\Voter\ElasticSearchEngineFeatureVoter
        arguments:
            - '@oro_website_search.engine.parameters'
        tags:
            - { name: oro_featuretogle.voter }

    Oro\Bundle\CustomerRecommendationBundle\Checker\Voter\CustomerRecommendationVoter:
        class: Gally\OroPlugin\Voter\ElasticSearchEngineFeatureVoter
        arguments:
            - '@oro_website_search.engine.parameters'
        tags:
            - { name: oro_featuretogle.voter }

imports:
    - { resource: services/sdk.yml }
    - { resource: services/indexer.yml }
    - { resource: services/search.yml }
