system_configuration:
    groups:
        gally_group:
            title: gally.configuration.group.label
            icon: fa-search

    fields:
        gally_oro.enabled:
            data_type: boolean
            type: Oro\Bundle\ConfigBundle\Form\Type\ConfigCheckbox
            priority: 50
            page_reload: true
            options:
                label: gally.configuration.field.enabled.label
                tooltip: gally.configuration.field.enabled.tooltip

        gally_oro.url:
            data_type: string
            type: Symfony\Component\Form\Extension\Core\Type\TextType
            priority: 40
            options:
                label: gally.configuration.field.url.label
                tooltip: gally.configuration.field.url.tooltip
                constraints:
                    - Url: ~

        gally_oro.check_ssl:
            data_type: boolean
            type: Oro\Bundle\ConfigBundle\Form\Type\ConfigCheckbox
            priority: 30
            options:
                label: gally.configuration.field.check_ssl.label
                tooltip: gally.configuration.field.check_ssl.tooltip

        gally_oro.email:
            data_type: string
            type: Symfony\Component\Form\Extension\Core\Type\TextType
            priority: 20
            options:
                label: gally.configuration.field.email.label
                tooltip: gally.configuration.field.email.tooltip
                constraints:
                    - Email: ~

        gally_oro.password:
            data_type: string
            type: Oro\Bundle\FormBundle\Form\Type\OroEncodedPlaceholderPasswordType
            priority: 10
            options:
                label: gally.configuration.field.password.label
                tooltip: gally.configuration.field.password.tooltip

    tree:
        system_configuration:
            commerce:
                children:
                    search:
                        children:
                            gally_group:
                                children:
                                    gally_group:
                                        children:
                                            - gally_oro.url
                                            - gally_oro.check_ssl
                                            - gally_oro.email
                                            - gally_oro.password
                                            - gally_oro.enabled

        website_configuration:
            commerce:
                children:
                    search:
                        children:
                            gally_group:
                                children:
                                    gally_group:
                                        children:
                                            - gally_oro.enabled
