Oro\Bundle\WebCatalogBundle\Entity\ContentNode:
    alias: oro_content_node_WEBSITE_ID
    fields:
        - name: id
          type: text
        - name: parentId
          type: text
        - name: path
          type: text
        - name: level
          type: integer
        - name: name
          type: text
        - name: description
          type: text

Oro\Bundle\ProductBundle\Entity\Brand:
    fields:
        - name: id
          type: integer

Oro\Bundle\ProductBundle\Entity\Product:
    fields:
        - name: inv_qty
          type: decimal
        - name: category_paths
          type: text
        - name: category_paths.CATEGORY_PATH
          type: text
        - name: visible_for_customer
          type: text
        - name: hidden_for_customer
          type: text

Oro\Bundle\WebsiteSearchSuggestionBundle\Entity\Suggestion:
    fields:
        - name: id
          type: integer
