Oro\Bundle\WebCatalogBundle\Entity\WebCatalog:
    alias: oro_web_catalog_WEBSITE_ID
    fields:
        - name: id
          type: text
        - name: parentId
          type: text
        - name: path
          type: text
        - name: level
          type: integer
        - name: name
          type: text
        - name: description
          type: text

Oro\Bundle\ProductBundle\Entity\Brand:
    fields:
        - name: id
          type: integer

Oro\Bundle\ProductBundle\Entity\Product:
    fields:
        - name: id
          type: integer
