Oro\Bundle\WebCatalogBundle\Entity\ContentNode:
    alias: oro_content_node_WEBSITE_ID
    fields:
        - name: id
          type: text
        - name: parentId
          type: text
        - name: path
          type: text
        - name: level
          type: integer
        - name: name
          type: text
        - name: description
          type: text

Oro\Bundle\ProductBundle\Entity\Brand:
    fields:
        - name: id
          type: integer

Oro\Bundle\ProductBundle\Entity\Product:
    fields:
        - name: id
          type: integer
        - name: inv_qty
          type: decimal
        - name: visibility_customer.customer_id
          type: text
        - name: visibility_customer.value
          type: integer

Oro\Bundle\WebsiteSearchSuggestionBundle\Entity\Suggestion:
    fields:
        - name: id
          type: integer
