Oro\Bundle\WebCatalogBundle\Entity\ContentNode:
    alias: oro_content_node_WEBSITE_ID
    fields:
        - name: id
          type: text
        - name: parentId
          type: text
        - name: path
          type: text
        - name: level
          type: integer
        - name: name
          type: text
        - name: description
          type: text
        - name: tree
          type: text
        - name: url
          type: text

Oro\Bundle\ProductBundle\Entity\Brand:
    fields:
        - name: id
          type: integer
