name: QA

on:
  push:
    branches:
      - master
      - '[1-9].[0-9]+.x'
      - 'feature-[a-z]+'
  pull_request: ~

jobs:
  qa:
    name: Code-Quality-Checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
      - uses: php-actions/composer@v6
        with:
          php_version: "8.2"
          php_extensions: ctype curl gd intl pcntl zip soap
          args: --no-plugins
      - name: Php cs fixer
        run: php ./vendor/bin/php-cs-fixer fix --diff --dry-run src
      - name: Phpstan
        run: php ./vendor/bin/phpstan --memory-limit=1G analyse
      - name: Phpunit
        run: php ./vendor/bin/phpunit src
